import type { Metadata } from "next";
import "@/app/(main)/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import SupabaseAuthListener from "@/components/supabase-auth-listener";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "EduTrack",
    description: "Generated by EDUTRACK",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="antialiased" suppressHydrationWarning>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SupabaseAuthListener />
                    {children}
                    <Toaster position="bottom-right" richColors />
                </ThemeProvider>
            </body>
        </html>
    );
}