import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import SupabaseAuthListener from "@/components/supabase-auth-listener";
import { Toaster } from "sonner";
import { DeletionWarningBanner } from "@/features/settingss/components/deletion-warning-banner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    display: "swap",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "EduTrack",
    description: "Generated by EDUTRACK",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                suppressHydrationWarning={true}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SupabaseAuthListener />

                    <SidebarProvider>
                        <AppSidebar />
                        <SidebarInset>
                            {/* Deletion warning banner — shows on every page if pending */}
                            <DeletionWarningBanner />
                            <main className="min-w-0">
                                <div className="absolute top-2 left-2 z-50">
                                    <SidebarTrigger className="fixed hover:bg-gray-200" />
                                </div>
                                {children}
                            </main>
                        </SidebarInset>
                    </SidebarProvider>
                </ThemeProvider>
                <Toaster position="bottom-right" richColors />
            </body>
        </html>
    );
}
