import type { Metadata } from "next";
import "@/app/(main)/globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "EduTrack",
    description: "Generated by EDUTRACK",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            {children}
            <Toaster position="bottom-right" richColors />
        </>
    );
}